const englishAlphabet = Array.from({ length: 26 }, (_, index) => String.fromCharCode(97 + index));
const uppercaseAlphabet = Array.from({ length: 26 }, (_, index) => String.fromCharCode(65 + index));
const numbers = Array.from({ length: 10 }, (_, index) => index.toString());
const specialCharacters = ['.', ',', '!', '?', '%', ':', ';', ' ', "'", '"', '-'];

export const combinedChars = [
  ...englishAlphabet,
  ...uppercaseAlphabet,
  ...numbers,
  ...specialCharacters,
];

export const sentences = [
  'The sun sets behind the mountains, casting a golden hue over the land.',
  'A curious cat investigates a new addition to its surroundings.',
  'In the quiet of the night, stars twinkle in the vast expanse of the sky.',
  'The aroma of freshly baked bread fills the air, making mouths water.',
  'Waves crash against the shore, creating a soothing rhythm.',
  'Laughter echoes through the park as children play on the swings.',
  'With a camera in hand, a photographer captures the beauty of nature.',
  'Raindrops pitter-patter on the windowpane, creating a gentle melody.',
  'Lost in thought, she gazes out the window, watching the world go by.',
  'A gentle breeze rustles the leaves, bringing relief from the summer heat.',
  'An old bookshop exudes a comforting scent of paper and ink.',
  'Birds chirp in the early morning, announcing the arrival of a new day.',
  'With a backpack slung over his shoulder, he sets off on an adventure.',
  'The city lights sparkle like jewels against the backdrop of the night.',
  'A rainbow arches across the sky after a passing rain shower.',
  'The distant call of a train whistle evokes a sense of nostalgia.',
  'The smell of freshly brewed coffee wafts through the cozy cafe.',
  'A field of wildflowers sways in the breeze, a riot of colors.',
  'The sound of a violin fills the concert hall, captivating the audience.',
  'Leaves crunch underfoot as they take a leisurely stroll through the woods.',
  'The scent of pine needles hangs in the air in the midst of a forest.',
  'With a canvas and brushes in hand, an artist brings a scene to life.',
  'Fireflies dance in the warm summer air, illuminating the night.',
  'A gentle stream meanders through a meadow, reflecting the sky.',
  'The aroma of a home-cooked meal draws everyone to the dinner table.',
  'A smile lights up her face as she reunites with an old friend.',
  'The first snowfall covers the landscape in a blanket of white.',
  'The crackling of a campfire provides warmth and companionship.',
  'Music fills the air as a street musician plays a soulful melody.',
  'A lighthouse stands tall, guiding ships safely through the dark.',
  'The soft glow of candles creates an atmosphere of serenity.',
  'The city comes to life as neon signs illuminate the streets.',
  'Stars shine brightly in the night sky, forming constellations.',
  'The hush of a library is broken only by the turning of pages.',
  'The bustling market is a tapestry of colors, scents, and sounds.',
  'A hammock sways gently between two trees, inviting relaxation.',
  'Footsteps echo on cobblestone streets, telling tales of the past.',
  'The scent of rain-soaked earth fills the air after a summer shower.',
  'A hot air balloon drifts lazily across the horizon.',
  'Seagulls soar over the ocean, their calls carried by the wind.',
  'A smile shared between strangers brings a moment of connection.',
  'As night falls, city lights transform the skyline into a painting.',
  'Autumn leaves crunch beneath their feet as they explore the woods.',
  'The clinking of glasses accompanies laughter at a lively party.',
  'The distant hum of traffic lulls the city into a peaceful slumber.',
  'A park bench offers a quiet spot for reflection and solitude.',
  'Fog rolls in, shrouding the landscape in a mystical veil.',
  'A couple dances under the stars, lost in the magic of the moment.',
  'The scent of pine fills the air as Christmas trees stand tall.',
  'A sailboat glides gracefully across the calm waters of a lake.',
  'A solitary figure watches the sunset from a rocky cliff.',
  'Rainbows emerge after a summer rain, a burst of vibrant color.',
  "A cathedral's intricate stained glass windows tell stories of old.",
  'As night descends, fireflies create a breathtaking light show.',
  'The melody of a violin drifts from an open window, captivating all who listen.',
  'The sun casts long shadows as it sets behind the mountains.',
  'The sweet aroma of blooming flowers fills the garden.',
  'The sound of waves crashing lulls beachgoers into relaxation.',
  'A cozy cabin by the lake offers respite from the busy world.',
  'A street artist creates vibrant masterpieces with each stroke of paint.',
  'Leaves fall gently from the trees, carpeting the ground in gold.',
  'A pair of lovebirds share tender moments on a park bench.',
  'A snow-covered landscape sparkles under the winter sun.',
  'The chirping of crickets creates a soothing nighttime symphony.',
  'An old bridge crosses a tranquil river, a testament to history.',
  'The warmth of a bonfire brings comfort on a chilly evening.',
  'A winding path leads through a meadow filled with wildflowers.',
  'The scent of freshly baked apple pie wafts from the kitchen.',
  'The skyline is painted with hues of pink and orange during sunrise.',
  'Leaves rustle as a gentle breeze sweeps through the forest.',
  'The sound of church bells fills the air, marking the passing hours.',
  'A horse-drawn carriage offers a romantic tour of the city.',
  'Stars twinkle in the clear night sky, each one a distant dream.',
  'The laughter of children echoes in the playground on a sunny day.',
  'The rustling of palm trees is a soothing backdrop to a tropical paradise.',
  'A cozy fireside chat brings friends together on a winter evening.',
  'The moon casts a silvery glow over a peaceful countryside.',
  'A field of sunflowers turns its vibrant faces toward the sun.',
  'The bustling market is alive with the vibrant energy of the city.',
  'Leaves crunch beneath their feet as they hike through the woods.',
  'The scent of pine and campfire smoke fills the air at a campsite.',
  'A violinist plays a haunting melody in the dimly lit concert hall.',
  'A snow-covered village is a picture of tranquility on a winter day.',
  'Seagulls cry out as they ride the ocean breeze along the shore.',
  'The soft glow of lanterns illuminates a quaint cobblestone street.',
  'Autumn leaves swirl in the wind, creating a colorful spectacle.',
  'The aroma of fresh rain permeates the air after a summer storm.',
  'A leisurely boat ride along a river offers moments of serenity.',
  'The cityscape transforms into a sea of lights as night falls.',
  'A cozy reading nook is bathed in soft light from a nearby window.',
  'The call of a distant train evokes feelings of nostalgia.',
  'Sunlight filters through the trees, creating dappled patterns on the ground.',
  'The scent of blooming flowers heralds the arrival of spring.',
  'The laughter of friends enjoying a picnic fills the park.',
  'Waves gently lap against the shore, a soothing rhythm of the sea.',
  'A lone hiker reaches the summit, rewarded with breathtaking views.',
  'The melody of a guitar drifts on the breeze, serenading passersby.',
  'The city awakens as dawn breaks, its energy building with each passing minute.',
  'The scent of freshly cut grass fills the air on a warm summer day.',
  'Stars blanket the night sky, a reminder of the vastness of the universe.',
];
